################################################################################
# This file was auto-generated by generate_eom.py
################################################################################
import numpy as np


def calculate_eom(x, u, m, g, ell, b, k1, k2):
    [theta, thetadot] = x.flatten()  # ensure 1D
    [tau] = u.flatten()  # ensure 1D
    eom = np.array([[thetadot], [(-b*thetadot - g*m*np.cos(theta) - k1*theta - k2*theta**3 + tau)/(ell**2*m)]])
    return eom.squeeze()
